### ISSUE TITLE
[question] Different properties per breakpoint

### ISSUE THREAD

**Issue by 2silver** [lukaskleinschmidt/snug#4]
Hi,
we investigate whether your tool suits our needs or not...

Is a setup - different properties per breakpoint possible?
This is one possible use-case
```css
.container { width: 100%; }

@media screen and (min-width: 768px) {
    .md\:container {
        max-width: 768px;
    }
}
@media screen and (min-width: 1024px) {
    .lg\:container {
        max-width: 1024px;
    }
}
@media screen and (min-width: 1280px) {
    .xl\:container {
        max-width: 1280px;
    }
}
```

**Comment by lukaskleinschmidt** [comment]
This is actually not something you would need this lib for directly.
But in the context of using it alongside I would go for a simple `@each` loop.

```scss
@use '@snug/core' as * with (
  $breakpoints: (
    'md': 768px,
    'lg': 1024px,
    'xl': 1280px,
  )
);

@each $key, $value in $breakpoints {
  @media screen and (min-width: #{$value}) {
    .#{$key}\:container {
      max-width: $value;
    }
  }
}
```

**Comment by 2silver** [comment]
Thanks, so simple.... 

```scss
.container {
    width: 100%;
}
@each $key, $value in $breakpoints {
    @media screen and (min-width: #{$value}) {
        .#{$key}\:container {
            max-width: $value;
        }
    }
}

```
